"""New Migration

Revision ID: 15e82f9d7e5e
Revises: eb93136fe3f2
Create Date: 2022-09-27 09:00:06.124459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15e82f9d7e5e'
down_revision = 'eb93136fe3f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artists')
    op.create_table('artists',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(), nullable=True),
    sa.Column('lname', sa.String(), nullable=True),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('alias', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('artist_id')
    )    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
