"""New Migration

Revision ID: 1a2b3eb6bfe8
Revises: 15e82f9d7e5e
Create Date: 2022-09-27 16:22:44.385749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a2b3eb6bfe8'
down_revision = '15e82f9d7e5e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
