"""New Migration

Revision ID: 9bc818d44443
Revises: 0f8f58ac1c55
Create Date: 2022-09-30 11:28:39.577858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bc818d44443'
down_revision = '0f8f58ac1c55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
