"""New Migration

Revision ID: eb93136fe3f2
Revises: 65a8b18e8024
Create Date: 2022-09-25 19:59:50.585890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb93136fe3f2'
down_revision = '65a8b18e8024'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
